<?php

use Illuminate\Foundation\Inspiring;
use Illuminate\Support\Facades\Artisan;

Artisan::command('inspire', function () {
    $this->comment(Inspiring::quote());
})->purpose('Display an inspiring quote');

Artisan::command('site-content:update-icon-list', function () {
    $svgPath = base_path('vendor/mallardduck/blade-lucide-icons/resources/svg');

    if (! is_dir($svgPath)) {
        $this->error('Lucide icons path not found: ' . $svgPath);
        $this->info('Run: composer require mallardduck/blade-lucide-icons');

        return 1;
    }

    $files = glob($svgPath . '/*.svg');
    $icons = [];
    foreach ($files as $file) {
        $name = basename($file, '.svg');
        $icons[$name] = implode(' ', array_map('ucfirst', explode('-', $name)));
    }
    ksort($icons, SORT_NATURAL);

    $configPath = config_path('icons.php');
    $lines = [
        '<?php',
        '',
        'return [',
        '    /*',
        '    |--------------------------------------------------------------------------',
        '    | Lucide icon names (key) => label for dropdown.',
        '    | default = icon key used when feature has no or invalid icon.',
        '    | Generated by: php artisan site-content:update-icon-list',
        '    |--------------------------------------------------------------------------',
        '    */',
        "    'default' => 'list-checks',",
    ];
    foreach ($icons as $key => $label) {
        $lines[] = "    " . var_export($key, true) . " => " . var_export($label, true) . ",";
    }
    $lines[] = '];';
    $lines[] = '';

    file_put_contents($configPath, implode("\n", $lines));

    $this->info('Updated ' . $configPath . ' with ' . count($icons) . ' icons.');
})->purpose('Update config/icons.php with all Lucide icons from blade-lucide-icons');
